[package]
name = "betterpmap"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
diff = "0.1.13"
libc = "0.2.161"
sysinfo = "0.32.0"
thiserror = "1.0.66"
